# Copyright (c) 2024 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
# - Philippe Sauter <phsauter@iis.ee.ethz.ch>

services:
  pulp-docker:
    build:
      dockerfile_inline: |
        FROM hpretl/iic-osic-tools:2024.10
        RUN pip install --user hjson mistletoe mako
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    volumes:
      - ./:/fosic/designs/croc
    stdin_open: true
    tty: true
    working_dir: /fosic/designs/croc
    entrypoint: /dockerstartup/scripts/ui_startup.sh
    command: --skip bash
